//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanThucAnNhanh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_MONAN_DATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CT_MONAN_DATHANG()
        {
            this.CTHOADONs = new HashSet<CTHOADON>();
        }
    
        public int MADATHANG { get; set; }
        public string MAMONAN { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<double> GIABAN { get; set; }
    
        public virtual DATHANG DATHANG { get; set; }
        public virtual MONAN MONAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHOADON> CTHOADONs { get; set; }
    }
}
